// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi7atekbuAqHF71RwC6qUnaUg4ytfVsbA',
    appId: '1:132369818025:web:2b3149e97c7aa594f124b8',
    messagingSenderId: '132369818025',
    projectId: 'directory-app-f9dd5',
    authDomain: 'directory-app-f9dd5.firebaseapp.com',
    storageBucket: 'directory-app-f9dd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6feqQq1g-lMCPT3XmSMU1wuv2ytlr1do',
    appId: '1:132369818025:android:f9d69fbaeb75a125f124b8',
    messagingSenderId: '132369818025',
    projectId: 'directory-app-f9dd5',
    storageBucket: 'directory-app-f9dd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGGGkUuFJzq18DKfBxbPODaoU9xdj7wVc',
    appId: '1:132369818025:ios:9bbcee5044cca690f124b8',
    messagingSenderId: '132369818025',
    projectId: 'directory-app-f9dd5',
    storageBucket: 'directory-app-f9dd5.appspot.com',
    iosBundleId: 'com.example.flutterDirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGGGkUuFJzq18DKfBxbPODaoU9xdj7wVc',
    appId: '1:132369818025:ios:63fb13a95dea928df124b8',
    messagingSenderId: '132369818025',
    projectId: 'directory-app-f9dd5',
    storageBucket: 'directory-app-f9dd5.appspot.com',
    iosBundleId: 'com.example.flutterDirectoryApp.RunnerTests',
  );
}
